/**
 * @file stm32_uart_transmit_example.c
 * @brief Example snippet showing how STM32G474RE transmits WaveForge telemetry over UART.
 * 
 * Works with STM32CubeMX HAL (e.g. USART2 / UART1).
 */

#include "waveforge_protocol.h"

/* External UART handle generated by STM32CubeMX */
extern UART_HandleTypeDef huart2;

void Send_Waveforge_Telemetry(float temp_c, float turbidity_ntu, float depth_pot_m, float sal_pot_psu) {
    WaveforgeTelemetry_t telemetry;
    char tx_buffer[WAVE_PACKET_MAX_LEN];

    /* 1. Fill Environmental Inputs */
    telemetry.temperature       = temp_c;         /* Real Sensor (ADC) */
    telemetry.turbidity         = turbidity_ntu;  /* Real Sensor (ADC) */
    telemetry.depth_proxy       = depth_pot_m;    /* Potentiometer ADC */
    telemetry.salinity_proxy    = sal_pot_psu;    /* Potentiometer ADC */

    /* 2. Fill Current STM32 Waveform Parameters */
    telemetry.center_frequency  = 100.0f;         /* 100 kHz baseline target */
    telemetry.bandwidth         = 50.0f;          /* 50 kHz bandwidth target */
    telemetry.pulse_duration    = 20;             /* 20 ms pulse */
    telemetry.amplitude         = 80;             /* 80% DAC output */

    /* 3. Pack into standard WaveForge packet with XOR checksum */
    int len = waveforge_pack(&telemetry, tx_buffer, sizeof(tx_buffer));

    if (len > 0) {
        /* 4. Transmit over UART to ESP32 (Non-blocking or standard HAL) */
        HAL_UART_Transmit(&huart2, (uint8_t*)tx_buffer, (uint16_t)len, 100);
    }
}
